### ISSUE TITLE
Upgrading Node.js to 20

### ISSUE THREAD

**Issue by LVMVRQUXL** [gradle/wrapper-validation-action#160]
Because [Node.js 16 actions are deprecated](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20), it could be nice to upgrade this action to Node.js 20.

Here's an example of workflow using [gradle/wrapper-validation-action@v1.0.6](https://github.com/gradle/wrapper-validation-action/tree/v1.0.6) that shows the corresponding deprecation notice: [Kotools Types Integration #370](https://github.com/kotools/types/actions/runs/6632215483).

Thank you for considering this issue.

**Comment by bigdaz** [comment]
This fix is available in the [v2.0.0-rc.1](https://github.com/gradle/wrapper-validation-action/releases/tag/v2.0.0-rc.1) release.

Please use `gradle/wrapper-validation-action@v2` instead of `v1`.

**Comment by LVMVRQUXL** [comment]
> This fix is available in the [v2.0.0-rc.1](https://github.com/gradle/wrapper-validation-action/releases/tag/v2.0.0-rc.1) release.
> 
> Please use `gradle/wrapper-validation-action@v2` instead of `v1`.

@bigdaz Do you have a visibility on when the version `2.0.0` will be available as a **stable** release (not only as a release candidate)?

**Comment by TWiStErRob** [comment]
Thank you @bigdaz! I already saw it ran successfully without warning on 10 repos from a few different orgs.

**Comment by bigdaz** [comment]
> Do you have a visibility on when the version 2.0.0 will be available as a stable release (not only as a release candidate)?

@LVMVRQUXL Likely a week or so: just want to let it soak a little. Unless we experience issues, the final release will be from the same commit.

**Comment by TWiStErRob** [comment]
Note that by pushing `v2` bots thing that it's a final release and most give no indication:
https://github.com/detekt/detekt/pull/6918 (pinned Renovate)
https://github.com/gradle-nexus/publish-plugin/pull/313 (non-pinned Renovate)
https://github.com/hiteshprajapati/fineract/pull/109 (pinned Dependabot)
https://github.com/syoon2/Project-Diagram-Generator/pull/47 (non-pinned Dependabot)

Only non-pinned Dependabot gets the release notes, so users see v2.0.0-rc.1 when they expand that.
