### ISSUE TITLE
`check-dist.yml` GitHub workflow does not work properly

### ISSUE THREAD

**Issue by Marcono1234** [gradle/wrapper-validation-action#171]
The `check-dist.yml` workflow of this repository does not seem to work properly. If I understand it correctly, it is supposed to detect whether `/dist/index.js` has been properly updated.

However, the workflow only runs `npm run build`, which does not update the `/dist` directory. I think it should run `npm run pack` instead.

Or alternatively if it is not desired that users commit the `/dist/index.js` in their pull requests, maybe there should be one workflow which fails in case users commit this file. And another workflow which runs on `main` and automatically updates `/dist/index.js`?

**Comment by bigdaz** [comment]
Good catch!
I presume this was originally copied from the `gradle-build-action` repository, where `npm run build` does indeed build the dist directory.
I've pushed a fix so this is consistent between projects I work on.

Yes, ideally we'd have a workflow that generates the `dist` directory on any push to `main`, and prohibits direct changes to `dist` in a PR. But for now that's a manual process, with a (broken until now) check.

**Comment by bigdaz** [comment]
First attempt failed. Testing in #172
