### ISSUE TITLE
Merge/call validation during setup-gradle

### ISSUE THREAD

**Issue by TWiStErRob** [gradle/wrapper-validation-action#173]
Assumption 1: this action is planned to be moved to the `gradle/actions` repo.

Assumption 2: #167 means the action will run even faster than before, with near 0 cost (~ glob file system search).

Would it be feasible / useful to call this action right before each setup-gradle? And I mean merging the two actions.

That's the recommendation anyways, so might as well integrate it. Both will be cloned anyway, so could be one, or at least embedding the js of one into the other.

Initially this could be behind a `validate: true` input of setup-gradlea, and later (v4?) become the default.

(This is just to start a conversation, feel free to close if it doesn't make sense, or move to another repo as you see fit.)

**Comment by bigdaz** [comment]
Yes, there's long been an issue for this on `gradle-build-action`: https://github.com/gradle/actions/issues/12. It just never became high enough priority.

I just transferred the issue over to the `gradle/actions` repository.

Moving this action into `gradle/actions/wrapper-validation` would probably make this easier to implement, but it is by no means critical to do so.
