### ISSUE TITLE
Introduce minimum expected count verification

### ISSUE THREAD

**Issue by JLLeitschuh** [gradle/wrapper-validation-action#3]
A simple contributor bypass would be to use a non-standard unicode character set for the `gradle-wrapper.jar`. For example, naming the file `gradlе-wrapper.jar`.

(If you didn't spot it, in the last one the `е` is actually a Crillic 'Yo' character, not the standard English 'e')

To mitigate this sort of attack, the solution is to simply verify that there is a minimum expected number of `gradle-wrapper.jar` files. If there are fewer, then we fail the check.

**Comment by eskatos** [comment]
Fixed by https://github.com/gradle/wrapper-validation-action/commit/9393a6ed9826e954408dfad70e6f8bccb4ff09be
