### ISSUE TITLE
Feature: Notify/optional fail, if its not using the newest Gradle version 

### ISSUE THREAD

**Issue by hfhbd** [gradle/wrapper-validation-action#32]
Currently, Dependabot cannot check the Gradle version, https://github.com/dependabot/dependabot-core/issues/2223.
Until Dependabot can check the version, it would be awesome, if this action can do this.

Goal:
Notify the developer using the GitHub action output, if there is a newer version.
Maybe there could also be an optional flag to fail the action, if a newer version is found. This flag should be disabled by default.

**Comment by JLLeitschuh** [comment]
The scope of this action is narrowly defined as a security verification check. I think that this would be more appropriate as a separate action independent of this one.
