### ISSUE TITLE
Request timeout error for version of Gradle that I never used

### ISSUE THREAD

**Issue by eygraber** [gradle/wrapper-validation-action#46]
I randomly get the following error using v1:

`Error: Request timeout: /distributions/gradle-6.8-rc-4-wrapper.jar.sha256`

I currently use 7.1.1 and never used 6.80-rc-4

**Comment by JLLeitschuh** [comment]
How regularly do you see this issue?

**Comment by eygraber** [comment]
I haven't seen it since filing the issue, and I only saw it a few times overall.

**Comment by JLLeitschuh** [comment]
@eskatos are we keeping the existing connection open when we retry? Should we try to make sure we're opening a new connection when we retry? Thoughts?

**Comment by bigdaz** [comment]
This should be fixed by #167
