### ISSUE TITLE
new version with vulnerability fixes

### ISSUE THREAD

**Issue by eirnym** [gradle/wrapper-validation-action#52]
There's few vulnerabilities has been fixed since last version. Is there anything new version has not been published?

**Comment by IdiosApps** [comment]
@eirnym which version were you on that had those issues? Is there a new version with the fixes (i.e. can this ticket be closed?)

**Comment by jbeckers** [comment]
This issue is about 89eda1fdc0167f59521d2bb10767f7169fb4d018 which is not yet in a release.

**Comment by jbeckers** [comment]
This was fixed in 1.0.5
