### ISSUE TITLE
Adding a new dedicated workflow for validation should be discouraged

### ISSUE THREAD

**Issue by erichaagdev** [gradle/wrapper-validation-action#94]
Adding a new dedicated workflow for validation should be discouraged. A new dedicated workflow will not stop any other workflows from running that may execute a Gradle wrapper. In other words, if a bad wrapper is contributed then by the time the wrapper validation fails, or by the time a maintainer notices, the bad wrapper may have already been executed in other workflows.

The _Add a new dedicated Workflow_ section should either be removed, or strongly discouraged. The recommendation should be to add the validation immediately after checkout on any workflow that may execute a Gradle wrapper.

**Comment by JLLeitschuh** [comment]
I think that's reasonable. I think that maybe offering a "here's the best way to do this" and a "here's how to do this if you're just using this GH action alone, and your CI is executed elsewhere"?

**Comment by bigdaz** [comment]
I think this should be done as part of https://github.com/gradle/actions/issues/12.
